apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "az-auto-tag-deployment.fullname" . }}
  labels:
{{ include "az-auto-tag-deployment.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "az-auto-tag-deployment.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "az-auto-tag-deployment.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:          
          - name: "AZURE_TENANT_ID"
            valueFrom:
              secretKeyRef:
                key:  tenantid
                name: {{ .Release.Name }}auth
          - name: "AZURE_CLIENT_ID"
            valueFrom:
              secretKeyRef:
                key:  clientid
                name: {{ .Release.Name }}auth
          - name: "AZURE_CLIENT_SECRET"
            valueFrom:
              secretKeyRef:
                key:  secret
                name: {{ .Release.Name }}auth
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
