apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}auth
data:
  clientid: {{ required "clientid required" .Values.config.clientid | b64enc }}
  tenantid: {{ required "tenantid required" .Values.config.tenantid | b64enc }}
  secret: {{ required "secret required" .Values.config.secret | b64enc }}